site_name: "Custom Q App with Jira Plugin"
site_description: "Documentation for the Custom Q App with Jira Plugin"
# docs_dir defaults to "docs"; keep docs in /docs folder as used belo

# MkDocs automatically looks inside the /docs folder
nav:
  - Home: index.md
  - Create Custom Q Application: create-custom-q-app.md
  - Create Jira Data Source: create-data-connection-with-jira.md
  - Create App in Jira for Auth: create-jira-app-oath.md
  - Launch and Test: launch-and-test.md

theme:
  name: material
  palette:
    primary: indigo
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

# If you use plugins or extra requirements, add them here and add to requirements.txt
plugins:
  - search